Добрый день
JRaven13/java-shareit pull request #1
Opened 2023-12-28 11:16 UTC by JRaven13

2023-12-29 06:20 UTC, VadimZharkov commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
В след спринте БД) Поэтому все что касается БД буду проверять в след раз.

2023-12-29 06:21 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +public class ErrorHandler {
Нужно добавить логгирование и обработку Throwable в статус INTERNAL_SERVER_ERROR

2023-12-29 06:24 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/enums/Status.java
> +package ru.practicum.shareit.enums;
Обычно пакет по типу не называют. Статус относится к бронированиию, значит туда и надо его поместить.

2023-12-29 06:25 UTC, VadimZharkov commented on src/main/resources/schema.sql
> +    email VARCHAR(40)
Для email недостаточная длина выбрана.

2023-12-29 06:26 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +
Нужно добавить логгирование в контроллеры

2023-12-29 06:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addItem(@RequestHeader(USERID_HEADER) Long userId, @RequestBody Item item) {
Контроллеры на вход и выход работают с DTO. C моделью работают классы сервиса и стораджа.

2023-12-29 06:30 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemStorageImpl.java
> +    private final UserService userService;
В сторадже не должно быть зависимости от сервиса. Общая цепочка зависимостей Контроллер->Сервис->Сторадж

2023-12-29 06:34 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/validator/ItemValidator.java
> +public class ItemValidator {
Уже пора переходить на валидацию с помощью аннотаций (@Valid @Validated @NotBlank и т.д.)

2023-12-29 06:35 UTC, VadimZharkov requested changes
Нужно исправить замечания.

2023-12-29 09:19 UTC, JRaven13 commented on pom.xml
> +			<artifactId>spring-boot-starter-jdbc</artifactId>
ок

2024-03-26 06:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +@ControllerAdvice
На курсе принято использовать `@RestControllerAdvice`. Эта та же по сути аннотация что и `@ControllerAdvice`, только `@ResponseBody` писать не нужно

2024-03-26 06:30 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/ErrorHandler.java
> +    public Map<String, String> handleGeneral(final RuntimeException e) {
Вместо мапы лучше сделать свай классик ErrorResponse и возвращать его.

2024-03-26 06:32 UTC, VadimZharkov requested changes
Можно улучшить

2024-04-01 07:19 UTC, VadimZharkov approved these changes
Да так

2024-05-17 05:56 UTC, JRaven13 commented
1

2024-05-17 08:07 UTC, merged