Add item requests
JRaven13/java-shareit pull request #3
Opened 2024-05-05 10:14 UTC by JRaven13

2024-05-06 08:35 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (from < 0 || size < 0) {
size не может также принимать значение 0, т.к. дальше как минимум деление на 0 может возникнуть.

2024-05-06 08:36 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Map<String, String> handleBadRequestException(final InvalidEntityException e) {
Нужно сделать единообразно и во всех методах возвращать  ErrorResponse

2024-05-06 08:41 UTC, VadimZharkov commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +public class BookingRepositoryTest {
Для тестов репозиториев нужно воспользоваться аннотацией `@DataJpaTest`

2024-05-06 08:43 UTC, VadimZharkov requested changes
Нужно исправить замечания и также добавить тестирование dto объектов с помощью  аннотации `@JsonTest`

2024-05-14 06:06 UTC, JRaven13 commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        if (from < 0 || size < 0) {
<=

2024-05-14 06:49 UTC, JRaven13 commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    public Map<String, String> handleBadRequestException(final InvalidEntityException e) {
ок

2024-05-17 06:08 UTC, JRaven13 commented
У меня теперь не проходит постман тесты

2024-05-17 08:26 UTC, JRaven13 commented
Комит

2024-05-17 11:21 UTC, VadimZharkov requested changes
Нет тестов, реализованных  с помощью `@DataJpaTest и @JsonTest`.

2024-05-19 07:17 UTC, JRaven13 commented
Моя тяжело даётся последние 3 спринта

2024-05-20 05:59 UTC, VadimZharkov approved these changes

2024-07-06 09:23 UTC, merged